language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install flake8>=3.8.2 flake8-bugbear>=20.1.4 pep8-naming>=0.10.0
  - pip install black>=19.10b0
script:
  - black --check .
  - flake8
